### ISSUE TITLE
After changing focus between input fields, text continue typing in previous input field

### ISSUE THREAD

**Issue by alexrosh** [tmeshkova/mozilla-central#1]
Simple test:
./qmlMozEmbedTest -url 'data:text/html,<body><input><input></body>'

Type in one field, set focus on second field, and type again
Result: text typed in first field.

**Comment by romaxa** [comment]
IIUC in latest build it is already fixed after IME implementation refactor for pre-edit/swype.

**Comment by tmeshkova** [comment]
fixed in 57a1312120da686dbce17a7d4d46f7b9a873e840, 64781fbd120fecd38631e29a958ebed1e840e930, 5189a2da1c1d904f4620f216a16a336aab11ad02, 2cbda160f29b2e12dfccb8b8c21acde104ac9132
