### ISSUE TITLE
crash [@ RPCChannel::~RPCChannel]

### ISSUE THREAD

**Issue by tmeshkova** [tmeshkova/mozilla-central#5]
caught while closing yahoo.com:

<code>
#0  0x411a87fc in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:45
#1  0x3c585728 in nsProfileLock::FatalSignalHandler (signo=11, info=0x3edfdf90, context=0x3edfe010)

```
at /mozilla-embedlite/obj-build-n9-qt/toolkit/profile/nsProfileLock.cpp:180
```
#2  <signal handler called>
#3  0x3c1a5ef8 in mozalloc_abort (msg=<value optimized out>) at /mozilla-embedlite/memory/mozalloc/mozalloc_abort.cpp:30
#4  0x3d50631c in NS_DebugBreak_P (aSeverity=3, aStr=<value optimized out>, aExpr=<value optimized out>, aFile=<value optimized out>,

```
aLine=656) at /mozilla-embedlite/xpcom/base/nsDebugImpl.cpp:409
```
#5  0x3d28d34c in mozilla::ipc::RPCChannel::DebugAbort (this=<value optimized out>, file=<value optimized out>, line=<value optimized out>,

```
cond=\<value optimized out\>, why=0x3de27f05 "mismatched CxxStackFrame ctor/dtors", type=0x3de27ce4 "rpc", reply=\<value optimized out\>)
at /mozilla-embedlite/ipc/glue/RPCChannel.cpp:656
```
#6  0x3d28d760 in mozilla::ipc::RPCChannel::~RPCChannel (this=0x409e8008, __in_chrg=<value optimized out>)

```
at /mozilla-embedlite/ipc/glue/RPCChannel.cpp:80
```
#7  0x3d2e1984 in mozilla::layers::PCompositorParent::~PCompositorParent (this=0x409e8000, __in_chrg=<value optimized out>)

```
at /mozilla-embedlite/obj-build-n9-qt/ipc/ipdl/PCompositorParent.cpp:122
```
#8  0x3d5caa20 in mozilla::layers::CompositorParent::~CompositorParent (this=0x409e8000, __in_chrg=<value optimized out>)

```
at /mozilla-embedlite/gfx/layers/ipc/CompositorParent.cpp:219
```
#9  0x3d1c09e0 in mozilla::embedlite::EmbedLiteCompositorParent::~EmbedLiteCompositorParent (this=0x409e8000,

```
__in_chrg=\<value optimized out\>) at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteCompositorParent.cpp:44
```
#10 0x3d1b8e70 in mozilla::embedlite::EmbedLiteCompositorParent::Release (this=0x409e8000)

```
at /mozilla-embedlite/embedding/embedlite/embedthread/EmbedLiteCompositorParent.h:21
```
#11 0x3d1c00f8 in DispatchToFunction<void (_)(mozilla::embedlite::EmbedLiteCompositorParent_, uint32_t), mozilla::embedlite::EmbedLiteCompositorParent*, unsigned int> (function=0x1, arg=<value optimized out>) at /mozilla-embedlite/ipc/chromium/src/base/tuple.h:454
#12 0x3d52f498 in MessageLoop::RunTask (this=0x3befd6e0, task=0x0)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:333
```
#13 0x3d531cc4 in MessageLoop::DeferOrRunPendingTask (this=0xa, pending_task=...)

```
at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:341
```
#14 0x3d531ea0 in MessageLoop::DoWork (this=0x3befd6e0) at /mozilla-embedlite/ipc/chromium/src/base/message_loop.cc:441
#15 0x3d28a3a0 in mozilla::ipc::DoWorkRunnable::Run (this=<value optimized out>)

```
at /mozilla-embedlite/ipc/glue/MessagePump.cpp:42
```
#16 0x3d4fdaf0 in nsThread::ProcessNextEvent (this=0x3bed3d00, mayWait=<value optimized out>, result=0x3edfe8c7)

```
at /mozilla-embedlite/xpcom/threads/nsThread.cpp:627
```
#17 0x3d4c15b8 in NS_ProcessPendingEvents_P (thread=0x3bed3d00, timeout=20)

```
at /mozilla-embedlite/obj-build-n9-qt/xpcom/build/nsThreadUtils.cpp:188
```
#18 0x3d19bf88 in nsBaseAppShell::NativeEventCallback (this=0x40466ce8)

```
at /mozilla-embedlite/widget/xpwidgets/nsBaseAppShell.cpp:97
```
#19 0x3d186b24 in nsAppShell::event (this=0xa, e=<value optimized out>) at /mozilla-embedlite/widget/qt/nsAppShell.cpp:90
#20 0x41f05f04 in QVolatileImageData::QVolatileImageData (this=0x40466ce0) at image/qvolatileimagedata.cpp:50
#21 0x41f100e8 in QPngHandlerPrivate::readImageFormat (this=0x40443670) at image/qpnghandler.cpp:557

---Type <return> to continue, or q <return> to quit---
#22 0x4176cfa0 in QString (this=0x3be1b620) at ../../include/QtCore/../../src/corelib/tools/qstring.h:882
#23 QXmlStreamStringRef (this=0x3be1b620) at ../../include/QtCore/../../src/corelib/xml/qxmlstream.h:122
#24 QXmlStreamReaderPrivate::resolveTag (this=0x3be1b620) at xml/qxmlstream.cpp:1659
#25 0x417714f8 in QXmlStreamReaderPrivate::parse (this=0x3edfebe7) at xml/qxmlstream_p.h:1848
#26 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4
#27 0x4179ff38 in standalone_months_data () from /usr/lib/libQtCore.so.4

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
</code>

**Comment by romaxa** [comment]
Already fixed in 64b3639df3484911ced76f5db82c0987947b9498
